# Generated by Django 2.2.4 on 2020-12-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_that_job_app', '0005_auto_20201226_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='image',
        ),
    ]
